name: Expo Build and Release
on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android APK
        run: |
          eas build -p android --profile production --non-interactive --local --output ./app.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          name: Release ${{ github.ref_name }}-${{ github.run_number }}
          body: |
            Automated build from branch: ${{ github.ref_name }}
          files: ./app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
