name: Expo Cloud Build APK Release

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Start EAS Android APK Build
        id: build
        run: |
          BUILD_URL=$(eas build -p android --profile production --non-interactive --json | jq -r '.[0].artifacts.buildUrl')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download APK
        run: |
          curl -L "$BUILD_URL" -o 7or.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 7or-${{ github.ref_name }}
          name: Release  7or-${{ github.ref_name }}
          body: Automated APK build from branch ${{ github.ref_name }}
          files: 7or.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
